// planning-poker-ui/src/components/Room.tsx
import { Stack } from "@mui/material"
import Cards from "./Cards"
import Round from "./Round"

interface Props {
    name: string
    votes: Record<string, string>
    vote: (points: string) => void
}

const Room : React.FC<Props> = ({name, votes, vote}) => {
    return (
        <Stack>
          <Cards
            currentVote={votes[name]}
            onVote={(points) => {
              vote(points)
            }}
          />
          <Round votes={votes} />
        </Stack>
    )
}

export default Room

// planning-poker-vue/src/components/Room.vue
<script setup lang="ts">
import Round from './Round.vue'
import Cards from './Cards.vue'

defineProps<{
    name: string,
    room: number,
    votes: Record<string, string>
}>()

defineEmits<{
    (e: 'vote', vote: string): void
}>()

</script>

<template>
    <Cards @vote="vote => $emit('vote', vote)" :votes="votes" :name="name" />
    <Round :votes="votes" />
</template>
